/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _000393326_H_RPCGEN
#define _000393326_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vectores {
	int vector1[10];
	int vector2[10];
};
typedef struct vectores vectores;

#define PROGRAMA_PP_MRE 0x20000001
#define VERSION_PP_MRE 1

#if defined(__STDC__) || defined(__cplusplus)
#define productoPunto 1
extern  int * productopunto_1(vectores *, CLIENT *);
extern  int * productopunto_1_svc(vectores *, struct svc_req *);
#define rangoMedioEspecial 2
extern  float * rangomedioespecial_1(vectores *, CLIENT *);
extern  float * rangomedioespecial_1_svc(vectores *, struct svc_req *);
extern int programa_pp_mre_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define productoPunto 1
extern  int * productopunto_1();
extern  int * productopunto_1_svc();
#define rangoMedioEspecial 2
extern  float * rangomedioespecial_1();
extern  float * rangomedioespecial_1_svc();
extern int programa_pp_mre_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vectores (XDR *, vectores*);

#else /* K&R C */
extern bool_t xdr_vectores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_000393326_H_RPCGEN */
