/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "000393326.h"
#include <stdbool.h>

void
programa_pp_mre_1(char *host, int argc, char *argv[])
{
	CLIENT *clnt;
	int  *result_1;
	vectores  productopunto_1_arg;
	float  *result_2;
	vectores  rangomedioespecial_1_arg;
	int cantVector = (argc - 2)/2;
	bool pp=true;
	int max=0;

	for (int i = 0; i < cantVector; i++){
	    productopunto_1_arg.vector1[i] = atoi(argv[i+2]);
	    productopunto_1_arg.vector2[i] = atoi(argv[2+i+cantVector]);
	    //printf("vec1: %d\nvec2: %d\n",productopunto_1_arg.vector1[i],productopunto_1_arg.vector2[i]);
	}
	for(int i = 0; i < cantVector; i++){
	    if(productopunto_1_arg.vector1[i]>max){
		max = productopunto_1_arg.vector1[i];
	    }
	    /*else if(productopunto_1_arg.vector1[i]>max2){
		max2 = productopunto_1_arg.vector2[i];
		printf("max2=%d\n",max2);
	    }*/
	}
	for(int i = 0; i < cantVector; i++){
	    if(productopunto_1_arg.vector2[i]>max){
		max = productopunto_1_arg.vector2[i];
		pp=false;
		break;
	    }
	}
#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_PP_MRE, VERSION_PP_MRE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(pp==true){
		result_1 = productopunto_1(&productopunto_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Producto Punto = %d\n",*result_1);
	}
	else{
		result_2 = rangomedioespecial_1(&rangomedioespecial_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Medio Rango Especial = %f\n",*result_2);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */


}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_pp_mre_1 (host,argc,argv);
exit (0);
}
