/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "000393326.h"

int *
productopunto_1_svc(vectores *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 0;

	for(int i=0; i<10; i++){
	   result = result + argp->vector1[i]*argp->vector2[i];
	}

	return &result;
}

float *
rangomedioespecial_1_svc(vectores *argp, struct svc_req *rqstp)
{
	static float  result;

	result = 0;
	int minimoI = 0;
	int maximoI = 0;

	for(int i = 0; i<10; i++){
	   if(minimoI == 0 && argp->vector1[i]%2 != 0){
		minimoI = argp->vector1[i];
	   }
	   else if(argp->vector1[i]%2 != 0 && argp->vector1[i]<minimoI){
		minimoI = argp->vector1[i];
	   }
	}

	for(int i = 0; i<10; i++){
	   int sum = 0;
	   for(int j=1; j<argp->vector2[i]; j++){
		if(argp->vector2[i]%j==0)
			sum = sum+j;
	   }
	   if(sum != argp->vector2[i] && argp->vector2[i]>maximoI)
		maximoI = argp->vector2[i];
	}
	result = ((float)(minimoI + maximoI))/2;

	return &result;
}
